### ISSUE TITLE
Variable named incorrectly

### ISSUE THREAD

**Issue by LukeMondy** [pgaijin66/bc#16]
Howdy

https://github.com/pgaijin66/bc/blob/cea6969ef9ace8c0aea9603f31c034b3d0cef123/src/bc#L43-L44

Line 43 should probably be 
```
 local current_branch_name=$1 
```
It looks like it is working at the moment, because anywhere you call the function already has `current_branch_name` defined.

**Comment by pgaijin66** [comment]
Thank you for raising the issue Luke. This has been resolved in https://github.com/pgaijin66/bc/pull/17
